### ISSUE TITLE
MBM-CL XT1031 5.1 Republic Wireless

### ISSUE THREAD

**Issue by AdiSai** [Negan1911/MotoFlasher#2]
Where can I find the MBM-CL for this version?

**Comment by chipthetech** [comment]
You can't get the mbm-cl for 5.1 yet Motorola hasn't released them and your best hope is to send it for repair

**Comment by AdiSai** [comment]
There's aso no way to generate it from the image files, correct?

**Comment by chipthetech** [comment]
Yes contact Motorola 
On Feb 7, 2016 11:03, Adi Sai <notifications@github.com> wrote:There's aso no way to generate it from the image files, correct?
